### ISSUE TITLE
複数ワークスペースへの通知ができるようにする

### ISSUE THREAD

**Issue by shoito** [shoito/kot-chrome-assistant#19]
とあるユーザーの声より

**Comment by shoito** [comment]
複数ワークスペースの場合でも、同一チャンネル名への通知と制限を設ければ、複数チャンネル対応のときと似たやり方で低コストで対応は可能。

**Comment by shoito** [comment]
実装済み、検証待ち
https://github.com/shoito/kot-chrome-assistant/commit/c111004ac654b743505ef06b9a4355c3f9022cde

**Comment by Keiichi-Tokumichi** [comment]
@shoito 
こちらの機能ですが、弊社のほうでマルチーワークスペース運用を開始しようとしています。
この機能、すごく需要が高いです！（喉から手が出ます）

Sanbox環境にShoitoさんをご招待させていただくことで、検証・リリースをお願いすることは可能でしょうか？
お忙しいところ大変恐縮ですが、何卒ご検討いただけませんでしょうか。

**Comment by shoito** [comment]
@Keiichi-Tokumichi 久しぶりでちょっとびっくり。ちょっと時間かかるかもしれませんが検証しますよ。

**Comment by Keiichi-Tokumichi** [comment]
見ていただいて恐縮です！すごく助かります！お手間をとらせてしまいますので、お時間はshoitoさんのいいようにで。

もし、マルチワークスペースの検証に弊社の環境があった方がよい、とかでしたら情シスにかけあいます！

**Comment by Keiichi-Tokumichi** [comment]
弊社のSlack Sandbox環境にはいっていただくことを許可もらえました！
以降のやり取りはSlackのほうにゲスト招待をさせていただければと思いますので、Shoitoさんのご都合の良いときにコメントいただければと思います。

**Comment by shoito** [comment]
@Keiichi-Tokumichi https://github.com/shoito/kot-chrome-assistant/pull/35 で実装してみました。また週末に時間取れたところで検証します。

**Comment by Keiichi-Tokumichi** [comment]
ご対応ありがとうございます。ほんと感謝しかないです。

**Comment by shoito** [comment]
@Keiichi-Tokumichi https://github.com/shoito/kot-chrome-assistant/pull/35 のオプション画面からのテスト送信で複数 Slack ワークスペースへの連携を確認しました。
KOT の試せるアカウントはないので、Sandbox でゲスト招待いただいてその辺も会話できればと。

**Comment by shoito** [comment]
@hirobel KOTで検証協力ありがとうございました。環境がなかったので助かりました:+1:
おかげで先ほど、Chrome Webストアに新バージョンを公開できました。

@Keiichi-Tokumichi Slackで相談＆共有しておりましたがこちらリリース終わりました。
https://github.com/shoito/kot-chrome-assistant/pull/35

**Comment by Keiichi-Tokumichi** [comment]
@shoito 
@hirobel 
ありがとうございます。
お忙しいところアップデート&テストいただき、大変に感謝です。
リリース内容で実際に使って、動作確認をレポートさせていただきます。

**Comment by Keiichi-Tokumichi** [comment]
@shoito 
返信遅くなりました。こちらのSlackワークスペースでも振り分けうまくいきました。
3つチャンネルを指定する場合は1つのチャンネルに1つのトークンを対応させて記載させる必要があるのですね。
こちらもうまくできました。

ありがとうございます。

**Comment by shoito** [comment]
@Keiichi-Tokumichi 
ご確認ありがとうございました！
3つのチャンネル...。2つまでしか見てなかったので助かります。
