### ISSUE TITLE
King Of TIMEのURLを選択式にしてほしい

### ISSUE THREAD

**Issue by ynott** [shoito/kot-chrome-assistant#20]
KOTを押して、Slackに「出勤」と入力するのを忘れがちなので、何かよいものがないかと検索していてこちらにたどり着きました。非常に良さそうなアプリでしたので、使ってみようかと思ったのですが、私の会社のアカウントは別のKOTのサーバーに収容されているためURLが違っており、ログインできませんでした。

私の会社のアカウントログインのURLは、
https://s3.kingtime.jp/independent/recorder/personal/
となっていました。

これが使えるようになるととても便利だと思いますので(他の社員も使ってみたいと言っていました)、
s2.kingtime.jp と s3.kingtime.jp が選択式になっているとよいと思います。
（今のところs2とs3しかないようです）

お手数をおかけしますが、ご検討いただければ幸いです。

**Comment by shoito** [comment]
@ynott フィードバックありがとうございます。
s2, s3 と分かれてるんですね。sNまであるんだろう。
返事遅くなってしまってすいません。
オプションで手軽に設定できるようにできるか検討します。

**Comment by shoito** [comment]
@ynott 
こちらオプションでs2.kingtime.jpとs3.kingtime.jpを切り替えられるように対応したバージョンをストアに申請してます。

**Comment by shoito** [comment]
対応版が公開されました
