### ISSUE TITLE
Chrome 拡張機能 Manifest V3 への対応

### ISSUE THREAD

**Issue by shoito** [shoito/kot-chrome-assistant#28]
https://developers-jp.googleblog.com/2020/12/chrome-88-chrome-manifest-v3.html
> 現在、Manifest V3 は Chrome 88 ベータ版で試験運用版として利用できます。今後のリリースでは、すばらしい機能がさらに導入される予定です。Chrome ウェブストアでは、Chrome 88 が安定版になる 1 月中旬より、Manifest V3 拡張機能を受け付ける予定です。Manifest V2 拡張機能のサポートが終了する厳密な日付は決まっていませんが、Manifest V3 が安定版チャンネルに到達してから、少なくとも 1 年の移行期間が設けられます。スケジュールについては、今後数か月でさらに詳しくお伝えする予定です。

2021年の Manifest V2 -> V3 への移行期間中に対応をする。

**Comment by shoito** [comment]
https://developer.chrome.com/blog/mv2-transition/
> January 17, 2022: New Manifest V2 extensions will no longer be accepted by the Chrome Web Store. Developers may still push updates to existing Manifest V2 extensions, but no new Manifest V2 items may be submitted.
> January 2023: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

**Comment by shoito** [comment]
Migrating to Manifest V3
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by shoito** [comment]
@hirobel TRY ありがとうございます！PR 待ってます。

**Comment by hirobel** [comment]
@shoito 
PRを作りましたのでレビューをお願いしますー
https://github.com/shoito/kot-chrome-assistant/pull/29

釈迦に説法かもしれませんが、もしV3対応についてまだ把握していないところがおありな感じであればこちらを参照ください！一般的にV3対応でやるべきことも含めて、概要をまとめてみました。
Chrome拡張機能ManifestV3へ対応する方法（V2から） https://zenn.dev/katoaki/articles/4e7548b533d7b3
