### ISSUE TITLE
Chrome拡張に打刻画面が表示されなくなった

### ISSUE THREAD

**Issue by Keiichi-Tokumichi** [shoito/kot-chrome-assistant#37]
@shoito 

2024/3/10頃からChrome拡張内で打刻画面が表示されなくなっています。

<img width="240" alt="image" src="https://github.com/shoito/kot-chrome-assistant/assets/80370857/78eb0a70-1a0d-460c-9c32-e2a314688ac6">

ただし、Web画面「 https://s2.kingtime.jp/independent/recorder/personal/ 」で打刻をするとChrome拡張で設定されているSlack連携は動作していました。
Chrome拡張での画面表示のみ何か制限されているような挙動です。

**Comment by cm-iwata** [comment]
エラーログ等確認する限りKOT側でiframe内の表示を許可しないように設定変更が入ったみたいですね

![image](https://github.com/shoito/kot-chrome-assistant/assets/38879253/55d117f8-604b-45fb-af5e-5b284437824c)

![image](https://github.com/shoito/kot-chrome-assistant/assets/38879253/b7ae2b82-6818-4d62-9c8f-74e7d7f459d5)

**Comment by shoito** [comment]
@Keiichi-Tokumichi @cm-iwata レポートありがとうございます。
変更加わったんですね。
私が試せるKOT環境がなく、どなたか以下のブランチで確認協力いただけませんか？
https://github.com/shoito/kot-chrome-assistant/tree/feature/mod-headers

**Comment by haoyayoi** [comment]
ポップアップ読み込み動作及び打刻動作を確認できました。
<img width="479" alt="スクリーンショット 2024-03-11 12 27 18" src="https://github.com/shoito/kot-chrome-assistant/assets/18229/7b898864-0362-4a9f-92bf-1910962a005d">

**Comment by haoyayoi** [comment]
テスト送信にてSlack側に更新が発生することも確認済み。

**Comment by shoito** [comment]
@haoyayoi @Keiichi-Tokumichi @cm-iwata 検証ありがとうございました。
上記ブランチのバージョンをストアで公開しました。
マニフェストに `permission` の追加が必要になった影響で、各ユーザーの手元に更新反映後は自動的にChrome拡張機能が無効化されると思うので、手動で有効化が必要だと思います。
https://chromewebstore.google.com/detail/pifbdpooppfkllaiobkaoeocbfmpabaj?hl=ja

**Comment by Keiichi-Tokumichi** [comment]
@shoito 
迅速なご対応とデプロイありがとうございます！

@haoyayoi 
テストありがとうございます！
